version: '3.9'

services:
  app:
    image: fedesu/ahorrapp:latest
    container_name: ahorrappv2
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    environment:
      FLASK_ENV: ${FLASK_ENV}
      FLASK_APP: ${FLASK_APP}
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_COOKIE_SECURE: ${JWT_COOKIE_SECURE}
      JWT_COOKIE_CSRF_PROTECT: ${JWT_COOKIE_CSRF_PROTECT}
      JWT_COOKIE_SAMESITE: ${JWT_COOKIE_SAMESITE}
      JWT_COOKIE_DOMAIN: ${JWT_COOKIE_DOMAIN}
      FRONTEND_URL: ${FRONTEND_URL}
      N8N_WEBHOOK_URL: ${N8N_WEBHOOK_URL}
      PAYPAL_CLIENT_ID: ${PAYPAL_CLIENT_ID}
      PAYPAL_SECRET: ${PAYPAL_SECRET}
      PAYPAL_API_BASE: ${PAYPAL_API_BASE}
      PAYPAL_RETURN_URL: ${PAYPAL_RETURN_URL}
      PAYPAL_CANCEL_URL: ${PAYPAL_CANCEL_URL}
    ports:
      - "5100:5100"
    volumes:
      - ./instance:/app/backend/app/instance
    networks:
      - ahorrapp-network
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16
    container_name: postgresdb
    restart: always 
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s
    volumes:
      - ahorrappv2_pgdata:/var/lib/postgresql/data
    networks:
      - ahorrapp-network

networks:
  ahorrapp-network:
    driver: bridge

volumes:
  ahorrappv2_pgdata:
    driver: local
